# Generated by Django 3.1.5 on 2021-02-18 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuenta_bancaria',
            field=models.CharField(max_length=24, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}[0-9]{22}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}[0-9]{22}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Pendiente', 'Pendiente'), ('Atendida', 'Atendida'), ('Rechazada', 'Rechazada')], default='pendiente', max_length=9),
        ),
    ]
