# Generated by Django 3.1.5 on 2021-02-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Atendida', 'Atendida'), ('Rechazada', 'Rechazada')], default='pendiente', max_length=9),
        ),
    ]
