# Generated by Django 3.1.5 on 2021-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210218_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendida', 'Atendida'), ('Rechazada', 'Rechazada'), ('Aceptada', 'Aceptada')], default='pendiente', max_length=9),
        ),
    ]
