# Generated by Django 3.1.5 on 2021-02-18 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210218_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trabajador'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Atendida', 'Atendida'), ('Rechazada', 'Rechazada'), ('Aceptada', 'Aceptada'), ('Pendiente', 'Pendiente')], default='pendiente', max_length=9),
        ),
    ]
