# Generated by Django 3.1.5 on 2021-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210308_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('realizado', 'Realizado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Rechazada', 'Rechazada'), ('Aceptada', 'Aceptada'), ('Atendida', 'Atendida'), ('Pendiente', 'Pendiente')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio',
            field=models.FloatField(),
        ),
    ]
