# Generated by Django 3.1.5 on 2021-01-29 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210129_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuenta_bancaria',
            field=models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{20}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cif',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{1}\\d{7}[a-zA-Z0-9]{1}$', 'Escribe un CIF correcto.')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{20}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'Escribe un número de teléfono correcto.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}[a-z]{1}$', 'Escribe un DNI correcto.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'Escribe un número de teléfono correcto.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
