# Generated by Django 3.1.5 on 2021-03-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210309_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='trabajador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trabajador'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Atendida', 'Atendida'), ('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada'), ('Aceptada', 'Aceptada')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='vehiculo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vehiculo'),
        ),
    ]
