# Generated by Django 3.1.5 on 2021-01-30 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210129_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'Escribe un número de teléfono correcto.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'Escribe un número de teléfono correcto.')]),
        ),
    ]
