# Generated by Django 3.1.5 on 2021-01-30 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210130_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuenta_bancaria',
            field=models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}[0-9]{22}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}[0-9]{22}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('[0-9]{8}[A-Za-z]{1}', 'Escribe un DNI correcto.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)', 'Escribe un formato de email correcto.')]),
        ),
    ]
