# Generated by Django 3.1.5 on 2021-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210317_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Atendida', 'Atendida'), ('Pendiente', 'Pendiente')], default='pendiente', max_length=9),
        ),
    ]
