# Generated by Django 3.1.5 on 2021-01-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210130_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='administrador',
        ),
        migrations.AddField(
            model_name='administrador',
            name='persona',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.persona'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='persona',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.persona'),
        ),
    ]
