# Generated by Django 3.1.5 on 2021-02-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210203_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('aceptada', 'Aceptada'), ('atendida', 'Atendida')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='fecha',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tratamiento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tratamiento'),
        ),
    ]
