# Generated by Django 3.1.5 on 2021-02-06 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210205_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='password', max_length=55, validators=[django.core.validators.RegexValidator('^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$', 'Escribe una contraseña con al menos 8 caracteres, al menos una letra y un número')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (2, 'Trabajador'), (3, 'Cliente'), (4, 'Empresa')], default=3),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Atendida', 'Atendida'), ('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=55, unique=True),
        ),
    ]
