# Generated by Django 3.1.5 on 2021-02-06 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_auto_20210206_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('realizado', 'Realizado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Atendida', 'Atendida'), ('Pendiente', 'Pendiente')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
