# Generated by Django 3.1.5 on 2021-01-29 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuenta_bancaria',
            field=models.CharField(max_length=22, validators=[django.core.validators.RegexValidator('^[0-9]{20}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cif',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{1}\\d{7}[a-zA-Z0-9]{1}$', 'Escribe un CIF correcto.')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(max_length=22, validators=[django.core.validators.RegexValidator('^[0-9]{20}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{8}[a-z]{1}$', 'Escribe un DNI correcto.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.BigIntegerField(max_length=9),
        ),
    ]
