# Generated by Django 3.1.5 on 2021-01-29 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210129_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=254, validators=[django.core.validators.RegexValidator('^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$', 'Escribe una contraseña con al menos 8 caracteres, al menos una letra y un número')]),
        ),
    ]
