# Generated by Django 3.1.5 on 2021-01-30 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210130_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=22, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}[0-9]{22}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=22, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}[0-9]{22}$', 'Escribe una cuenta bancaria correcta.')]),
        ),
    ]
