DROP TABLE CLIENTES IF EXISTS;
DROP TABLE PERSONAS IF EXISTS;
DROP TABLE EMPRESAS IF EXISTS;
DROP TABLE USUARIOS IF EXISTS;

CREATE TABLE USUARIOS(
	EMAIL VARCHAR(50) PRIMARY KEY,
	CONTRASEÑA VARCHAR(50) NOT NULL
	);

CREATE TABLE EMPRESAS(
	NOMBRE VARCHAR(50) NOT NULL, 
	CIF VARCHAR(10) NOT NULL PRIMARY KEY,
	DIRECCION VARCHAR(255) NOT NULL,
	TELEFONO INTEGER NOT NULL,
	CUENTABANCARIA VARCHAR(24) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
	);

ALTER TABLE empresas ADD CONSTRAINT fk_empresas_usuarios FOREIGN KEY (email) REFERENCES usuarios (email);

CREATE TABLE PERSONAS(
	NOMBRE VARCHAR(50) NOT NULL, 
	DNI VARCHAR(9) NOT NULL PRIMARY KEY,
	TELEFONO INTEGER NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
	);

ALTER TABLE personas ADD CONSTRAINT fk_personas_usuarios FOREIGN KEY (email) REFERENCES usuarios (email);

CREATE TABLE CLIENTES(
	DIRECCION VARCHAR(255) NOT NULL,
	CUENTABANCARIA VARCHAR(24) NOT NULL,
	DNI VARCHAR(9) NOT NULL
	);

ALTER TABLE clientes ADD CONSTRAINT fk_clientes_personas FOREIGN KEY (dni) REFERENCES personas (dni);

	