# Generated by Django 3.1.5 on 2021-03-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210219_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_expedicion', models.DateField()),
                ('emisor', models.CharField(default='Dedesin SL', max_length=50)),
                ('receptor', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('importe', models.FloatField()),
                ('tipo_impositivo', models.FloatField(default=21)),
                ('fecha_operaciones', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Atendida', 'Atendida'), ('Rechazada', 'Rechazada')], default='pendiente', max_length=9),
        ),
        migrations.AddField(
            model_name='servicio',
            name='factura',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.factura'),
        ),
    ]
