# Generated by Django 3.1.5 on 2021-05-11 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210321_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('realizado', 'Realizado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Atendida', 'Atendida'), ('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada')], default='pendiente', max_length=9),
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicio')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.trabajador')),
            ],
        ),
    ]
