# Generated by Django 3.1.5 on 2021-06-01 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210511_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='trabajador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.trabajador'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('Atendida', 'Atendida'), ('Aceptada', 'Aceptada'), ('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada')], default='pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='plaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.plaga'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tratamiento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tratamiento'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
    ]
